# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

  config.vm.synced_folder "/home/funsun/code", "/code",
    type: "nfs",
    nfs_version: 4

  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 8
    libvirt.memory = 8192
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end

end
